<?php
/**
 * Created by PhpStorm.
 * User: mouedhen
 * Date: 25/03/18
 * Time: 23:32
 */

namespace App\Http\Resources\Auth;


use Illuminate\Http\Resources\Json\Resource;

class PermissionResource extends Resource
{
    public function toArray($request)
    {
        return parent::toArray($request); // TODO: Change the autogenerated stub
    }
}